### ISSUE TITLE
数据库是不是有问题啊

### ISSUE THREAD

**Issue by lhyinfinite** [sdibt/stuexam#3]
:(
以超级管理员身份登陆时，点击选择题 填空题啥的时候http://localhost/sdibtoj-master/stuexam/Teacher/Index/choose
会提示以下错误，没有 'question_type'，我想知道是哪里出了错呢
1054:Unknown column 'question_type' in 'where clause' [ SQL语句 ] : SELECT COUNT(*) AS tp_count FROM `ex_choose` WHERE ( 1=1 AND question_type = 0 AND isprivate = 0 ) LIMIT 1
错误位置

**Comment by sdibt** [comment]
数据库字段没做更新, 已更新~你重新同步下
