### ISSUE TITLE
少了JudgeOnline模块。

### ISSUE THREAD

**Issue by ljs1201** [sdibt/stuexam#4]
少了JudgeOnline模块。也没有loginpage.php的文件

**Comment by boxjan** [comment]
JudgeOnline 在 [sdibtoj](https://github.com/SDIBTACM/sdibtoj)下，这个项目是依赖于sdibtoj的，很抱歉给您带来困扰。（另 sdibtoj中包含一个stuexam，建议删除后，重新从本项目进行clone）

使用时，请修改sdibtoj/include/db_info.inc.php 以及stuexam/Index/Common/Conf/database.php中关于数据库的配置

**Comment by boxjan** [comment]
如果您还有任何问题的话，您可以重新打开此issue
